// カードデータ定義
// 仕様書 spec-v0.4.md のカード一覧表に準拠

const CARDS = [
  // ===== N レアリティ =====
  {
    id: 'mikeneko',
    name: '三毛猫',
    rarity: 'N',
    hp: 25,
    maxHp: 25,
    atk: 10,
    charm: 12,
    spd: 8,
    image: 'images/cat_001.svg',
    capriciousness: 6,
    slackAction: 'ぼーっとする',
    description: '気分によって動いたり動かなかったり',
  },
  {
    id: 'kuroneko',
    name: '黒猫',
    rarity: 'N',
    hp: 20,
    maxHp: 20,
    atk: 12,
    charm: 8,
    spd: 12,
    image: 'images/cat_002.svg',
    capriciousness: 4,
    slackAction: 'おびえる',
    description: '慎重すぎて腰が引けることも',
  },
  {
    id: 'shironeko',
    name: '白猫',
    rarity: 'N',
    hp: 30,
    maxHp: 30,
    atk: 8,
    charm: 10,
    spd: 10,
    image: 'images/cat_003.svg',
    capriciousness: 7,
    slackAction: 'グルーミングする',
    description: '自分磨きに忙しいことがある',
  },
  {
    id: 'toraneko',
    name: 'トラ猫',
    rarity: 'N',
    hp: 22,
    maxHp: 22,
    atk: 12,
    charm: 8,
    spd: 10,
    image: 'images/cat_004.svg',
    capriciousness: 3,
    slackAction: 'ぼーっとする',
    description: 'おおらかで頼りになる',
  },
  {
    id: 'sabineko',
    name: 'サビ猫',
    rarity: 'N',
    hp: 28,
    maxHp: 28,
    atk: 8,
    charm: 12,
    spd: 9,
    image: 'images/cat_005.svg',
    capriciousness: 6,
    slackAction: 'グルーミングする',
    description: '我が道を行く一匹狼',
  },
  {
    id: 'hachiware',
    name: 'ハチワレ',
    rarity: 'N',
    hp: 25,
    maxHp: 25,
    atk: 10,
    charm: 10,
    spd: 10,
    image: 'images/cat_006.svg',
    capriciousness: 4,
    slackAction: 'ぼーっとする',
    description: '穏やかで安心感がある',
  },
  {
    id: 'chatoraneko',
    name: 'チャトラ',
    rarity: 'N',
    hp: 22,
    maxHp: 22,
    atk: 11,
    charm: 9,
    spd: 11,
    image: 'images/cat_007.svg',
    capriciousness: 5,
    slackAction: '寝る',
    description: 'いつでもどこでも眠れる',
  },
  {
    id: 'kijitoraneko',
    name: 'キジトラ',
    rarity: 'N',
    hp: 20,
    maxHp: 20,
    atk: 12,
    charm: 8,
    spd: 12,
    image: 'images/cat_008.svg',
    capriciousness: 5,
    slackAction: 'おびえる',
    description: 'ちょっとしたことで固まる',
  },

  // ===== R レアリティ =====
  {
    id: 'american_shorthair',
    name: 'アメショ',
    rarity: 'R',
    hp: 35,
    maxHp: 35,
    atk: 15,
    charm: 15,
    spd: 15,
    image: 'images/cat_009.svg',
    capriciousness: 5,
    slackAction: 'ぼーっとする',
    description: '自分のペースを崩さない',
  },
  {
    id: 'russian_blue',
    name: 'ロシアンブルー',
    rarity: 'R',
    hp: 40,
    maxHp: 40,
    atk: 13,
    charm: 18,
    spd: 13,
    image: 'images/cat_010.svg',
    capriciousness: 3,
    slackAction: 'おびえる',
    description: '繊細だが芯は強い',
  },
  {
    id: 'bengal',
    name: 'ベンガル',
    rarity: 'R',
    hp: 30,
    maxHp: 30,
    atk: 18,
    charm: 13,
    spd: 18,
    image: 'images/cat_011.svg',
    capriciousness: 7,
    slackAction: 'ぼーっとする',
    description: '気分が乗れば無双する',
  },
  {
    id: 'norwegian',
    name: 'ノルウェージャン',
    rarity: 'R',
    hp: 40,
    maxHp: 40,
    atk: 15,
    charm: 15,
    spd: 13,
    image: 'images/cat_012.svg',
    capriciousness: 4,
    slackAction: '寝る',
    description: 'ゆったり構えて動じない',
  },
  {
    id: 'ragdoll',
    name: 'ラグドール',
    rarity: 'R',
    hp: 38,
    maxHp: 38,
    atk: 13,
    charm: 18,
    spd: 14,
    image: 'images/cat_013.svg',
    capriciousness: 6,
    slackAction: '寝る',
    description: '力が抜けてしまうことがある',
  },

  // ===== SR レアリティ =====
  {
    id: 'lion',
    name: 'ライオン',
    rarity: 'SR',
    hp: 45,
    maxHp: 45,
    atk: 30,
    charm: 15,
    spd: 18,
    image: 'images/cat_014.svg',
    capriciousness: 4,
    slackAction: '堂々としている',
    description: '常に堂々と存在感を放つ',
  },
  {
    id: 'munchkin',
    name: 'マンチカン',
    rarity: 'SR',
    hp: 45,
    maxHp: 45,
    atk: 15,
    charm: 30,
    spd: 18,
    image: 'images/cat_015.svg',
    capriciousness: 6,
    slackAction: 'グルーミングする',
    description: '興味が移るとそっちに夢中',
  },

  // ===== LR レアリティ =====
  {
    id: 'maneki_neko',
    name: '招き猫',
    rarity: 'LR',
    hp: 60,
    maxHp: 60,
    atk: 35,
    charm: 35,
    spd: 25,
    image: 'images/cat_016.svg',
    capriciousness: 1,
    slackAction: '輝いている',
    description: '黄金の輝きで場を支配する',
  },
];

// レアリティごとのドロー時アイテムポイント
const RARITY_ITEM_POINTS = {
  N: 3,
  R: 5,
  SR: 8,
  LR: 12,
};

// カードIDからカードデータを取得（ディープコピーして返す）
function getCardById(id) {
  const card = CARDS.find(c => c.id === id);
  return card ? JSON.parse(JSON.stringify(card)) : null;
}

// 全16種からランダムで指定枚数をドローする（重複なし）
function drawCards(count) {
  const shuffled = [...CARDS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map(c => JSON.parse(JSON.stringify(c)));
}
